
export const SEED_IDEAS = [
  {
    title: "DentalStock AI",
    niche: "Saúde & Bem-estar",
    pain: "Clínicas odontológicas perdem milhares de reais anualmente com má gestão de estoque. Materiais caros expiram ou faltam em procedimentos críticos.",
    solution: "Sistema de gestão de estoque com IA que prevê demanda e sugere compras automáticas ('Pedido Inteligente') baseado na agenda.",
    why: "O MVP é simples (entrada/saída) e o churn é baixo pois organiza o caos operacional da clínica.",
    pricing_model: "Assinatura (R$ 99 - R$ 249/mês)",
    target: "B2B (Clínicas Odontológicas)",
    sales_strategy: "Venda direta e parcerias com dentais.",
    pdr: "Stack: React, Node.js, Supabase. IA: Regressão linear simples para previsão de demanda baseada em histórico."
  },
  {
    title: "WhatsApp Recall para Clínicas",
    niche: "Saúde & Bem-estar",
    pain: "Clínicas têm base de clientes inativa e perdem receita recorrente por não chamar pacientes para retorno (limpeza, check-up).",
    solution: "Plugin que conecta à agenda e envia mensagens automáticas de recall via WhatsApp após período configurável (ex: 6 meses).",
    why: "Valor fácil de provar: um paciente que retorna paga a assinatura. Ferramenta vira vendedor silencioso.",
    pricing_model: "Assinatura (R$ 197 - R$ 297/mês)",
    target: "B2B (Clínicas de Estética/Odonto)",
    sales_strategy: "Demonstração do ROI com calculadora de recuperação.",
    pdr: "Integração com Google Calendar e API de WhatsApp (Waha/Twilio)."
  },
  {
    title: "NutriZap - Acompanhamento",
    niche: "Saúde & Bem-estar",
    pain: "Nutricionistas perdem pacientes que desistem do plano alimentar por falta de acompanhamento diário e motivação.",
    solution: "Chatbot de WhatsApp que envia perguntas diárias programadas ('Bebeu água?', 'Comeu fruta?') e gera relatório de adesão.",
    why: "Aumenta o valor percebido da consulta e a retenção do paciente. MVP é um construtor de fluxo simples.",
    pricing_model: "Assinatura (R$ 149 - R$ 299/mês)",
    target: "B2B (Nutricionistas)",
    sales_strategy: "Instagram marketing focado em nutricionistas.",
    pdr: "Backend para agendar mensagens e Webhook para receber respostas sim/não."
  },
  {
    title: "Diário de Bordo Cuidadores",
    niche: "Saúde & Bem-estar",
    pain: "Famílias com idosos sofrem ansiedade sem saber se o cuidador deu remédios ou alimentou o parente corretamente.",
    solution: "App de checklist compartilhado onde o cuidador marca tarefas (banho, remédio) e a família acompanha em tempo real.",
    why: "Venda baseada em paz de espírito para a família. Nicho em crescimento acelerado.",
    pricing_model: "Assinatura Família (R$ 39/mês)",
    target: "B2C (Famílias com idosos)",
    sales_strategy: "Parcerias com agências de cuidadores.",
    pdr: "App mobile simples (PWA) com realtime database."
  },
  {
    title: "Meu Pet em Dia",
    niche: "Pet",
    pain: "Donos esquecem vacinas anuais e clínicas veterinárias perdem receita recorrente previsível.",
    solution: "Carteira de vacinação digital com lembretes automáticos e módulo de 'Plano de Saúde Simplificado' para a clínica.",
    why: "Resolve dor dupla: saúde do pet e receita da clínica. Mercado Pet é apaixonado e gasta bem.",
    pricing_model: "Assinatura Clínica (R$ 199/mês)",
    target: "B2B (Veterinárias)",
    sales_strategy: "Venda direta para donos de clínicas.",
    pdr: "Sistema de cadastro de pets e cron jobs para envio de lembretes."
  },
  {
    title: "LaudoFácil Fisioterapeutas",
    niche: "Saúde & Bem-estar",
    pain: "Fisioterapeutas gastam horas escrevendo laudos e relatórios de evolução manualmente.",
    solution: "Gerador de laudos com templates prontos para condições comuns e biblioteca de exercícios em vídeo para anexar.",
    why: "Produtividade pura. Profissionaliza o entregável do fisioterapeuta.",
    pricing_model: "Assinatura (R$ 79/mês)",
    target: "B2B (Fisioterapeutas Autônomos)",
    sales_strategy: "Google Ads para 'modelo de laudo fisioterapia'.",
    pdr: "Editor de texto rico com blocos pré-definidos."
  },
  {
    title: "Gestão Segura Psicólogos",
    niche: "Saúde & Bem-estar",
    pain: "Psicólogos precisam de prontuário seguro (sigilo) e sofrem para cobrar pacientes e agendar sessões via WhatsApp.",
    solution: "Prontuário eletrônico criptografado com agendamento e pagamento integrado (link de pagamento).",
    why: "Segurança/Sigilo é obrigatório no nicho. Automatiza a parte chata (cobrança).",
    pricing_model: "Assinatura (R$ 99/mês)",
    target: "B2B (Psicólogos)",
    sales_strategy: "Parcerias com CRP ou grupos de recém-formados.",
    pdr: "Foco pesado em segurança de dados e criptografia no banco."
  },
  {
    title: "Gestor Validade Farmácia",
    niche: "Saúde & Bem-estar",
    pain: "Farmácias de manipulação perdem insumos caros que vencem na prateleira por falta de controle.",
    solution: "Controle de estoque focado em validade com alertas proativos e sugestão de campanhas de venda para itens quase vencendo.",
    why: "ROI direto: evitar perder um pote de insumo paga o software. Nicho regulado que precisa de compliance.",
    pricing_model: "Assinatura (R$ 150/mês)",
    target: "B2B (Farmácias de Manipulação)",
    sales_strategy: "Cold call e email marketing.",
    pdr: "Dashboard com 'Farol de Validade' (Verde/Amarelo/Vermelho)."
  },
  {
    title: "Estoque Lentes Óticas",
    niche: "Vendas",
    pain: "Vendedores de óticas pequenas perdem vendas demorando para achar lentes no estoque físico bagunçado.",
    solution: "App de inventário simples com leitor de código de barras via câmera para localizar lentes (Gaveta X, Posição Y).",
    why: "Resolve dor de venda imediata. Foco no pequeno varejista que não usa ERP complexo.",
    pricing_model: "Assinatura (R$ 89/mês)",
    target: "B2B (Pequenas Óticas)",
    sales_strategy: "Visitas locais e demonstração rápida.",
    pdr: "Mobile-first, uso da câmera para scan de código de barras."
  },
  {
    title: "Match Adoção Animais",
    niche: "Pet",
    pain: "Alto índice de devolução de animais adotados em ONGs por incompatibilidade de perfil com a família.",
    solution: "Plataforma estilo 'Tinder' que cruza perfil do animal com estilo de vida do adotante (casa/apto, tempo livre).",
    why: "Resolve dor emocional e logística das ONGs. Ajuda a profissionalizar o setor.",
    pricing_model: "Assinatura ONG (R$ 99/mês)",
    target: "B2B (ONGs e Protetores)",
    sales_strategy: "Abordagem via Instagram das ONGs.",
    pdr: "Algoritmo simples de matching (score de compatibilidade)."
  },
  {
    title: "Monitor Postura Webcam",
    niche: "Saúde & Bem-estar",
    pain: "Trabalhadores remotos desenvolvem dores nas costas por má postura sem perceber.",
    solution: "Software que usa a webcam e IA (computer vision) para alertar quando o usuário senta errado.",
    why: "Produto B2C de bem-estar escalável. Tecnologia de visão computacional está acessível.",
    pricing_model: "Anual (R$ 99/ano)",
    target: "B2C (Home Office Workers)",
    sales_strategy: "Ads em redes sociais focados em 'dor nas costas'.",
    pdr: "Uso de bibliotecas como MediaPipe ou TensorFlow.js no navegador."
  },
  {
    title: "ClientGuard Contadores",
    niche: "Finanças",
    pain: "Contadores perdem clientes e pagam multas por esquecer prazos de declarações fiscais.",
    solution: "Calendário automatizado de obrigações fiscais com alertas de risco e confirmação de leitura do cliente.",
    why: "Seguro contra multas. O churn é baixíssimo pois vira o cérebro do escritório.",
    pricing_model: "Assinatura (R$ 129 - R$ 599/mês)",
    target: "B2B (Escritórios Contabilidade)",
    sales_strategy: "Parcerias com sindicatos de contadores.",
    pdr: "Sistema robusto de jobs/cron para alertas de email/whatsapp."
  },
  {
    title: "Rastreador Marcas INPI",
    niche: "Jurídico",
    pain: "Empresas perdem suas marcas por não monitorar novos registros conflitantes no INPI semanalmente.",
    solution: "Robô que monitora o Diário Oficial do INPI e alerta se alguém tentar registrar marca parecida.",
    why: "Seguro barato para um ativo valioso. Custo da assinatura é ínfimo perto de perder a marca.",
    pricing_model: "Assinatura (R$ 29/marca/mês)",
    target: "B2B (Empresas e Advogados)",
    sales_strategy: "SEO para 'monitoramento de marca'.",
    pdr: "Scraper do site do INPI e processamento de texto (fuzzy matching)."
  },
  {
    title: "Calc. Rescisão Doméstica",
    niche: "Finanças",
    pain: "Empregadores domésticos têm medo de errar cálculo de demissão e sofrer processo trabalhista.",
    solution: "Calculadora simples que gera o cálculo exato e os documentos (TRCT, recibo) prontos para assinar.",
    why: "Venda baseada no medo. Mercado gigante de lares com empregados.",
    pricing_model: "Pagamento Único (R$ 49) ou Assinatura",
    target: "B2C (Empregadores Domésticos)",
    sales_strategy: "Google Ads para 'como calcular rescisão empregada'.",
    pdr: "Motor de cálculo trabalhista preciso (frontend logic)."
  },
  {
    title: "Contratos Freelance Blindados",
    niche: "Jurídico",
    pain: "Freelancers levam calote ou sofrem com escopo infinito por não terem contratos formais.",
    solution: "Gerador de contratos focado em proteção (pagamento adiantado, limite de alterações) com linguagem simples.",
    why: "Empoderamento do freelancer. Se paga no primeiro 'não calote'.",
    pricing_model: "Assinatura (R$ 39/mês)",
    target: "B2C (Designers, Devs, Redatores)",
    sales_strategy: "Parcerias com influencers de carreira freela.",
    pdr: "Gerador de PDF baseado em inputs de formulário."
  },
  {
    title: "Anonimizador LGPD",
    niche: "Jurídico",
    pain: "Advogados precisam tarjar nomes e dados sensíveis de centenas de páginas de processos manualmente.",
    solution: "Ferramenta que usa IA para identificar e tarjar nomes, CPFs e endereços em PDFs automaticamente.",
    why: "Compliance obrigatório e economia de horas de trabalho manual maçante.",
    pricing_model: "Assinatura (R$ 199/mês)",
    target: "B2B (Escritórios de Advocacia)",
    sales_strategy: "Demonstração direta da economia de tempo.",
    pdr: "Uso de NER (Named Entity Recognition) via API de NLP."
  },
  {
    title: "DocuSign Advogados",
    niche: "Jurídico",
    pain: "Ferramentas grandes de assinatura são caras para autônomos. Coletar assinatura física é lento.",
    solution: "Plataforma de assinatura eletrônica simples e com validade, focada no advogado autônomo, via WhatsApp.",
    why: "Nicho mal atendido pelos grandes players. A integração com WhatsApp agiliza o aceite do cliente.",
    pricing_model: "Assinatura (R$ 99/mês)",
    target: "B2B (Advogados Autônomos)",
    sales_strategy: "Marketing de conteúdo jurídico.",
    pdr: "Gerenciamento de certificados digitais e logs de assinatura."
  },
  {
    title: "Gerador Atas Reunião",
    niche: "Jurídico",
    pain: "Advogados gastam tempo redigindo atas de reunião societárias padronizadas.",
    solution: "Gerador de atas com banco de deliberações (textos prontos) para agilizar a formalização.",
    why: "Ferramenta de produtividade para nicho de alto valor hora.",
    pricing_model: "Assinatura (R$ 129/mês)",
    target: "B2B (Advogados Societários)",
    sales_strategy: "LinkedIn Outreach.",
    pdr: "Formulário dinâmico que monta documento Word/PDF."
  },
  {
    title: "Termos Quitação Trabalhista",
    niche: "Jurídico",
    pain: "Risco de processos futuros mesmo após acordo trabalhista se o termo não for robusto.",
    solution: "Gerador de termos de quitação com cláusulas de 'efeito geral' validadas juridicamente.",
    why: "Segurança jurídica. Valor percebido alto pelo risco que evita.",
    pricing_model: "Assinatura (R$ 89/mês)",
    target: "B2B (Advogados Trabalhistas/RH)",
    sales_strategy: "Conteúdo sobre prevenção de passivo trabalhista.",
    pdr: "Gerador de documentos simples."
  },
  {
    title: "ObraFácil Orçamentos",
    niche: "Construção Civil",
    pain: "Empreiteiros erram orçamentos usando papel e perdem dinheiro ou perdem a obra por preço alto.",
    solution: "Software de orçamento conectado a bases de preço (SINAPI) que gera proposta profissional.",
    why: "Profissionaliza o pequeno construtor e evita prejuízo.",
    pricing_model: "Assinatura (R$ 79/mês)",
    target: "B2B (Pequenos Construtores)",
    sales_strategy: "Parcerias com lojas de material de construção.",
    pdr: "Integração com APIs ou bases de dados de preços da construção."
  },
  {
    title: "ChangeOrder Rápido",
    niche: "Construção Civil",
    pain: "Mudanças de escopo 'de boca' na obra geram prejuízo e brigas no final.",
    solution: "App simples para registrar mudança, tirar foto, colocar preço e cliente dar 'ok' na hora.",
    why: "Resolve conflito financeiro. Simplicidade extrema é a chave.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2B (Mestres de Obra/Empreiteiros)",
    sales_strategy: "Viralização em grupos de WhatsApp da área.",
    pdr: "App mobile focado em UX simplificado para uso em campo."
  },
  {
    title: "LeadImob Corretor",
    niche: "Imobiliário",
    pain: "Corretores perdem leads de portais por demora no atendimento e falta de organização.",
    solution: "Mini-CRM que centraliza leads de portais e automatiza o primeiro 'Oi' no WhatsApp.",
    why: "Perder uma venda de imóvel custa milhares de reais. A ferramenta garante o atendimento rápido.",
    pricing_model: "Assinatura (R$ 89/mês)",
    target: "B2B (Corretores Autônomos)",
    sales_strategy: "Parcerias com imobiliárias e cursos de TTI.",
    pdr: "Integração com emails de leads dos portais (parser)."
  },
  {
    title: "Vistoria Voz p/ Texto",
    niche: "Imobiliário",
    pain: "Vistoriadores perdem horas digitando relatórios de fotos e anotações feitas em papel.",
    solution: "App onde o vistoriador dita as observações enquanto tira fotos e o sistema monta o laudo PDF.",
    why: "Economia brutal de tempo operacional. ROI fácil de medir.",
    pricing_model: "Assinatura (R$ 297/mês)",
    target: "B2B (Imobiliárias)",
    sales_strategy: "Venda direta para gerentes de locação.",
    pdr: "API de Speech-to-Text (Whisper/Google) e geração de PDF."
  },
  {
    title: "Gerador Descrição Imóveis",
    niche: "Imobiliário",
    pain: "Anúncios com descrições ruins geram poucos leads. Corretores têm dificuldade de escrita.",
    solution: "Ferramenta que usa IA para gerar descrições persuasivas baseadas nas características (3 quartos, vista mar).",
    why: "Melhora o ativo principal de marketing do corretor. Baixo custo, alto valor.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2B (Corretores)",
    sales_strategy: "Freemium (1 descrição grátis).",
    pdr: "Wrapper simples de GPT-4 com prompts otimizados para copy imobiliário."
  },
  {
    title: "Calculadora Flip Imóveis",
    niche: "Imobiliário",
    pain: "Investidores erram cálculo de reforma e venda (flip) e têm prejuízo.",
    solution: "Planilha SaaS que guia o cálculo de custos, impostos e prazos para validar viabilidade do flip.",
    why: "Ferramenta de decisão financeira para público com dinheiro. Evita prejuízos grandes.",
    pricing_model: "Assinatura (R$ 97/mês)",
    target: "B2C (Investidores Imobiliários)",
    sales_strategy: "Conteúdo sobre investimentos imobiliários.",
    pdr: "Lógica financeira complexa encapsulada em UI simples."
  },
  {
    title: "RepassePRO Aluguéis",
    niche: "Imobiliário",
    pain: "Gestão manual de repasse de aluguel para proprietários gera erros e desconfiança.",
    solution: "Sistema que automatiza o split de pagamento e gera extrato transparente para o proprietário.",
    why: "Transparência retém o cliente da imobiliária (proprietário).",
    pricing_model: "Taxa por transação (R$ 5)",
    target: "B2B (Pequenas Imobiliárias)",
    sales_strategy: "Venda consultiva.",
    pdr: "Integração com gateway de pagamento que suporte split (Asaas, Pagar.me)."
  },
  {
    title: "Marketplace Fotógrafos Imob",
    niche: "Imobiliário",
    pain: "Fotos ruins vendem menos, mas contratar fotógrafo caro para todo imóvel é inviável.",
    solution: "Uber de fotógrafos imobiliários. Preço fixo, padronizado, entrega rápida.",
    why: "Productized Service. Resolve dor de marketing da imobiliária.",
    pricing_model: "Por serviço (R$ 150/imóvel)",
    target: "B2B (Imobiliárias)",
    sales_strategy: "Parceria com imobiliárias locais.",
    pdr: "Plataforma de marketplace de serviços (agendamento e entrega de arquivos)."
  },
  {
    title: "Gestão Canteiro Obras",
    niche: "Construção Civil",
    pain: "Falta de registro do que acontece na obra gera atrasos e falhas de comunicação.",
    solution: "Diário de obra digital via app. Mestre de obras registra presença e fotos do dia.",
    why: "Registro legal e acompanhamento remoto para o engenheiro/dono.",
    pricing_model: "Assinatura por Obra (R$ 299/mês)",
    target: "B2B (Construtoras)",
    sales_strategy: "Venda para engenheiros.",
    pdr: "App mobile offline-first (funciona sem internet na obra)."
  },
  {
    title: "Aviso Chuva Obras",
    niche: "Construção Civil",
    pain: "Chuva inesperada estraga material (cimento) e serviços (concretagem).",
    solution: "Alerta meteorológico hiperlocalizado via WhatsApp para o mestre de obras.",
    why: "Seguro barato contra perdas materiais. Simples e útil.",
    pricing_model: "Assinatura (R$ 99/obra/mês)",
    target: "B2B (Engenheiros)",
    sales_strategy: "Demo gratuita em dias de chuva.",
    pdr: "API de meteorologia precisa e bot de WhatsApp."
  },
  {
    title: "Plugin Recupera Carrinho",
    niche: "E-commerce",
    pain: "Lojas perdem 70% das vendas em carrinhos abandonados.",
    solution: "Plugin simples (Shopify/Woo) que envia sequência de recuperação (Email/Zap) com 1 clique.",
    why: "ROI imediato. Se recuperar 1 venda, paga a ferramenta.",
    pricing_model: "Assinatura (R$ 49/mês) + %",
    target: "B2B (Lojistas E-commerce)",
    sales_strategy: "App Store dos marketplaces.",
    pdr: "Integração profunda com APIs de e-commerce e disparo de mensagens."
  },
  {
    title: "Auditor Fornecedor Drop",
    niche: "E-commerce",
    pain: "Dropshippers sofrem com fornecedores ruins (atraso, produto errado) e queimam a loja.",
    solution: "Extensão Chrome que dá nota para fornecedor AliExpress/Shopee baseado em histórico real oculto.",
    why: "Ferramenta de inteligência e redução de risco para o negócio.",
    pricing_model: "Assinatura (R$ 69/mês)",
    target: "B2B (Dropshippers)",
    sales_strategy: "Influencers de Dropshipping.",
    pdr: "Extensão de navegador e scraping de dados de reviews/envios."
  },
  {
    title: "Recuperador Pix",
    niche: "E-commerce",
    pain: "Muitos geram Pix e não pagam (esquecem ou não copiam código).",
    solution: "Sistema que detecta Pix não pago em 15min e manda o código 'copia e cola' no Zap do cliente.",
    why: "Aumenta conversão de boleto/pix drasticamente.",
    pricing_model: "Assinatura + Sucesso",
    target: "B2B (E-commerce brasileiro)",
    sales_strategy: "Integração com checkouts populares (Yampi, CartX).",
    pdr: "Webhooks de status de pedido e automação de msg."
  },
  {
    title: "Tabela Medidas Inteligente",
    niche: "E-commerce",
    pain: "Trocas por tamanho errado destroem a margem de lucro de lojas de roupa.",
    solution: "Widget que recomenda tamanho baseado em altura/peso e marcas que cliente já usa (sem fita métrica).",
    why: "Reduz logística reversa e aumenta confiança de compra.",
    pricing_model: "Assinatura (R$ 149/mês)",
    target: "B2B (E-commerce Moda)",
    sales_strategy: "Venda consultiva focada em redução de trocas.",
    pdr: "Algoritmo de recomendação baseado em dados antropométricos."
  },
  {
    title: "Editor Fotos em Massa",
    niche: "E-commerce",
    pain: "Lojistas perdem dias editando fotos de fornecedor (tirar fundo, logo) uma a uma.",
    solution: "Ferramenta web para upload em lote, remove fundo e padroniza com IA em minutos.",
    why: "Produtividade extrema para cadastro de produtos.",
    pricing_model: "Créditos ou Assinatura (R$ 59/mês)",
    target: "B2B (Lojistas)",
    sales_strategy: "SEO para 'remover fundo foto produto'.",
    pdr: "API de remoção de fundo (Remove.bg ou open source) e processamento em fila."
  },
  {
    title: "Alerta Ruptura Concorrente",
    niche: "E-commerce",
    pain: "Vendedores perdem chance de subir preço quando concorrente fica sem estoque.",
    solution: "Monitoramento de anúncio do concorrente. Avisa na hora quando acaba o estoque dele.",
    why: "Inteligência competitiva acionável para ganhar dinheiro rápido.",
    pricing_model: "Assinatura (R$ 89/mês)",
    target: "B2B (Sellers Mercado Livre/Amazon)",
    sales_strategy: "Grupos de sellers.",
    pdr: "Scraper frequente de páginas de produto."
  },
  {
    title: "Monitor Preços Niche",
    niche: "E-commerce",
    pain: "Perder a 'Buy Box' por centavos de diferença.",
    solution: "Repricing simples para pequenos sellers. Mantém preço X centavos abaixo do concorrente monitorado.",
    why: "Ferramenta essencial para competir em marketplace.",
    pricing_model: "Assinatura (R$ 149/mês)",
    target: "B2B (Sellers)",
    sales_strategy: "Apps do ecossistema dos marketplaces.",
    pdr: "Integração oficial com APIs de marketplace para alterar preços."
  },
  {
    title: "Plugin Compre Junto IA",
    niche: "E-commerce",
    pain: "Ticket médio baixo e recomendações manuais ineficientes.",
    solution: "Plugin que usa histórico da loja para sugerir combos que realmente fazem sentido (Quem comprou A levou B).",
    why: "Aumento automático de receita sem esforço do lojista.",
    pricing_model: "Assinatura (R$ 29/mês)",
    target: "B2B (Lojas WooCommerce)",
    sales_strategy: "Marketplace WordPress.",
    pdr: "Análise de dados de pedidos (Association Rule Mining)."
  },
  {
    title: "Gestão Afiliados WP",
    niche: "E-commerce",
    pain: "Criar programa de afiliados próprio é complexo ou caro.",
    solution: "Plugin simples para WooCommerce que cria links de afiliado e painel básico de comissões.",
    why: "Permite que pequenos lojistas tenham exército de vendas.",
    pricing_model: "Anual (R$ 99/ano)",
    target: "B2B (Infoprodutores/Lojistas)",
    sales_strategy: "SEO plugin wordpress.",
    pdr: "Plugin PHP leve com rastreamento de cookies."
  },
  {
    title: "Lista de Desejos + Alerta",
    niche: "E-commerce",
    pain: "Cliente gosta mas não compra agora, e a loja perde o contato.",
    solution: "Plugin de Wishlist que captura email e avisa automaticamente quando item baixa de preço.",
    why: "Recuperação de vendas e engajamento.",
    pricing_model: "Anual (R$ 49/ano)",
    target: "B2B (Lojas virtuais)",
    sales_strategy: "Demonstração de aumento de retorno.",
    pdr: "Sistema de gatilho de email baseado em mudança de preço."
  },
  {
    title: "Análise Sentimento Reviews",
    niche: "E-commerce",
    pain: "Marcas não têm tempo de ler milhares de reviews para saber o que melhorar.",
    solution: "IA que lê reviews da Amazon/Shopee e resume: 'Amam a bateria, odeiam a entrega'.",
    why: "Inteligência de produto rápida e barata.",
    pricing_model: "Assinatura (R$ 79/mês)",
    target: "B2B (Marcas/Fabricantes)",
    sales_strategy: "Relatórios de exemplo gratuitos.",
    pdr: "NLP para análise de sentimento e clusterização de tópicos."
  },
  {
    title: "ValidadePRO Mercadinhos",
    niche: "Varejo",
    pain: "Perda de produtos vencidos e risco de multa em pequenos mercados.",
    solution: "App de controle de validade simples com alerta de vencimento e sugestão de etiqueta de desconto.",
    why: "Transforma prejuízo certo em venda com desconto. ROI imediato.",
    pricing_model: "Assinatura (R$ 199/mês)",
    target: "B2B (Pequenos Mercados)",
    sales_strategy: "Visita porta a porta e representação.",
    pdr: "App mobile focado em agilidade de cadastro (scan)."
  },
  {
    title: "Estoque Consignado Moda",
    niche: "Varejo",
    pain: "Marcas perdem controle de peças deixadas em lojas parceiras (consignado).",
    solution: "Sistema onde a loja parceira dá baixa na venda e a marca vê estoque real em múltiplos locais.",
    why: "Viabiliza modelo de negócio consignado sem caos.",
    pricing_model: "Assinatura (R$ 199/mês)",
    target: "B2B (Pequenas Marcas de Roupa)",
    sales_strategy: "Feiras de moda e atacado.",
    pdr: "Sistema multi-tenant com portal para o parceiro."
  },
  {
    title: "Catálogo Digital Atacado",
    niche: "Vendas",
    pain: "Venda por PDF/WhatsApp é bagunçada e difícil de fechar pedido.",
    solution: "Catálogo web interativo com carrinho de atacado (regras de mínimo, grade de cor/tamanho).",
    why: "Melhora experiência de compra B2B e aumenta ticket.",
    pricing_model: "Assinatura (R$ 179/mês)",
    target: "B2B (Confecções/Distribuidores)",
    sales_strategy: "Migração de clientes que usam PDF.",
    pdr: "E-commerce simplificado sem checkout financeiro (apenas pedido)."
  },
  {
    title: "MenuDigital QR Inteligente",
    niche: "Alimentação",
    pain: "PDF no celular é horrível. Garçom demora para atender.",
    solution: "Cardápio web rápido com pedidos na mesa e 'Upsell Inteligente' (sugere bebida/sobremesa).",
    why: "Aumenta ticket médio e agiliza operação.",
    pricing_model: "Assinatura (R$ 119/mês)",
    target: "B2B (Restaurantes)",
    sales_strategy: "Parcerias com gráficas de cardápio.",
    pdr: "PWA de alta performance com sistema de pedidos."
  },
  {
    title: "ReviewBoost Restaurantes",
    niche: "Alimentação",
    pain: "Apenas cliente insatisfeito avalia. Nota no Google cai.",
    solution: "QR Code na mesa: 'Gostou?'. Sim -> Link Google. Não -> Feedback privado pro dono.",
    why: "Gestão de reputação simples e automática.",
    pricing_model: "Assinatura (R$ 99/mês)",
    target: "B2B (Bares e Restaurantes)",
    sales_strategy: "Teste grátis de 30 dias.",
    pdr: "Roteamento condicional simples web."
  },
  {
    title: "Tradutor Menu Turístico",
    niche: "Alimentação",
    pain: "Turistas não entendem cardápio traduzido pelo Google (Moqueca = Fish Stew?).",
    solution: "Cardápio digital com tradução contextual e fotos explicativas dos pratos locais.",
    why: "Melhora experiência do turista e venda de pratos mais caros.",
    pricing_model: "Anual (R$ 1200/ano)",
    target: "B2B (Restaurantes em áreas turísticas)",
    sales_strategy: "Venda local em polos turísticos.",
    pdr: "Uso de IA para traduções culturais gastronômicas."
  },
  {
    title: "Cardápio Sazonal Chef",
    niche: "Alimentação",
    pain: "Chefs querem mudar pratos toda semana mas imprimir é caro.",
    solution: "Cardápio digital focado em edição ultra-rápida pelo celular do chef. Destaque 'Prato do Dia'.",
    why: "Flexibilidade e redução de custo de gráfica.",
    pricing_model: "Assinatura (R$ 149/mês)",
    target: "B2B (Bistrôs/Restaurantes Autorais)",
    sales_strategy: "Influencers de gastronomia.",
    pdr: "CMS mobile-first extremamente simples."
  },
  {
    title: "Calculadora Buffet",
    niche: "Alimentação",
    pain: "Calcular comida para evento é difícil: sobra prejuízo, falta vergonha.",
    solution: "Calculadora que gera lista de compras exata baseada em perfil de convidados e duração.",
    why: "Segurança no planejamento. Evita desperdício.",
    pricing_model: "Assinatura (R$ 69/mês)",
    target: "B2B (Buffets/Churrasqueiros)",
    sales_strategy: "SEO 'calculadora churrasco'.",
    pdr: "Algoritmo ajustado de consumo per capita."
  },
  {
    title: "GiftCardFácil Local",
    niche: "Varejo",
    pain: "Pequeno comércio perde venda de presente por não ter sistema de vale-presente.",
    solution: "Sistema simples para vender e validar Gift Cards digitais em lojas físicas.",
    why: "Nova receita e aquisição de clientes (quem ganha vai na loja).",
    pricing_model: "Taxa (5%)",
    target: "B2B (Comércio Local)",
    sales_strategy: "Venda para associações comerciais.",
    pdr: "Gerador e validador de códigos únicos (QR)."
  },
  {
    title: "NotaryFlow Cartórios",
    niche: "Jurídico",
    pain: "Processos manuais e clientes ligando para saber status de documento.",
    solution: "Workflow visual (Kanban) para cartórios com portal de acompanhamento para o cliente.",
    why: "Nicho com dinheiro e sistemas legados ruins. Melhora atendimento.",
    pricing_model: "Assinatura (R$ 499/mês)",
    target: "B2B (Cartórios)",
    sales_strategy: "Eventos notariais.",
    pdr: "Sistema de gestão de status e notificações."
  },
  {
    title: "FitClass Manager",
    niche: "Saúde & Bem-estar",
    pain: "Estúdios perdem tempo agendando aulas e repondo faltas no WhatsApp.",
    solution: "App de agendamento com sistema de créditos e lista de espera automática.",
    why: "Automatiza a operação. Lista de espera garante aula cheia.",
    pricing_model: "Assinatura (R$ 149 - R$ 299/mês)",
    target: "B2B (Pilates/Yoga)",
    sales_strategy: "Indicação entre donos de estúdio.",
    pdr: "Lógica de agendamento e gestão de pacotes de aulas."
  },
  {
    title: "Roteirizador Entregas Locais",
    niche: "Logística",
    pain: "Entregadores fazem rotas ineficientes gastando mais gasolina.",
    solution: "App simples: digite 5 endereços, ele ordena a melhor rota e abre no Waze.",
    why: "Economia direta de combustível e tempo. ROI diário.",
    pricing_model: "Assinatura (R$ 59/mês)",
    target: "B2B (Pizzarias/Farmácias)",
    sales_strategy: "Venda para gerentes de delivery.",
    pdr: "API Google Maps/Mapbox para otimização de rota (TSP)."
  },
  {
    title: "Lembrete Manutenção Oficina",
    niche: "Vendas",
    pain: "Oficinas esperam carro quebrar e não vendem preventivas.",
    solution: "CRM simples que avisa cliente: 'Faz 6 meses da troca de óleo, agende agora'.",
    why: "Gera receita recorrente e fideliza cliente.",
    pricing_model: "Assinatura (R$ 129/mês)",
    target: "B2B (Oficinas Mecânicas)",
    sales_strategy: "Visita presencial.",
    pdr: "Cadastro de veículo e automação de datas."
  },
  {
    title: "Controle Lavanderia Quilo",
    niche: "Varejo",
    pain: "Roupas misturadas e perda de peças em lavanderias.",
    solution: "Sistema de rastreio com etiquetas QR Code por lote de cliente.",
    why: "Organização básica para evitar prejuízo de repor roupa perdida.",
    pricing_model: "Assinatura (R$ 99/mês)",
    target: "B2B (Lavanderias)",
    sales_strategy: "Associações de lavanderias.",
    pdr: "Impressão de etiquetas e fluxo de status."
  },
  {
    title: "Agendamento Salão Beleza",
    niche: "Saúde & Bem-estar",
    pain: "Buracos na agenda entre serviços de tempos diferentes.",
    solution: "Agendamento online com 'Encaixe Inteligente' (tetris de horários) para maximizar ocupação.",
    why: "Otimiza faturamento preenchendo ociosidade.",
    pricing_model: "Assinatura (R$ 179/mês)",
    target: "B2B (Salões de Beleza)",
    sales_strategy: "Instagram e parcerias com distribuidores de cosméticos.",
    pdr: "Algoritmo de alocação de recursos/tempo."
  },
  {
    title: "Estou a Caminho (Click & Collect)",
    niche: "Varejo",
    pain: "Cliente chega para retirar e pedido não está pronto (ou esfriou).",
    solution: "Botão 'Estou a Caminho' que avisa a loja baseada na localização do cliente (GPS) para preparar na hora certa.",
    why: "Sincronia perfeita, produto fresco, cliente feliz.",
    pricing_model: "Assinatura (R$ 79/mês)",
    target: "B2B (Restaurantes/Lojas)",
    sales_strategy: "Venda focada em experiência do cliente.",
    pdr: "Geolocalização do browser e cálculo de ETA."
  },
  {
    title: "Ordem Serviço Assistência",
    niche: "Varejo",
    pain: "Cliente liga toda hora para saber se celular tá pronto.",
    solution: "OS Digital com Portal do Cliente via QR Code para consultar status online.",
    why: "Reduz atendimento telefônico e passa profissionalismo.",
    pricing_model: "Assinatura (R$ 89/mês)",
    target: "B2B (Assistência Técnica)",
    sales_strategy: "Google Ads local.",
    pdr: "CRUD de OS com página pública de status."
  },
  {
    title: "Termo Consentimento Tatuagem",
    niche: "Jurídico",
    pain: "Papelada de termos legais se perde e ocupa espaço.",
    solution: "App tablet para assinatura digital do termo + foto do documento do cliente anexada.",
    why: "Segurança jurídica e organização digital.",
    pricing_model: "Assinatura (R$ 69/mês)",
    target: "B2B (Estúdios Tattoo)",
    sales_strategy: "Convenções de tatuagem.",
    pdr: "Captura de assinatura (canvas) e upload de foto."
  },
  {
    title: "TestimonialFlow Cursos",
    niche: "Creator Economy",
    pain: "Difícil coletar depoimentos em vídeo de alunos.",
    solution: "Link único onde aluno grava vídeo direto no navegador e autoriza uso. Centraliza tudo.",
    why: "Prova social vende. Facilitar a coleta aumenta a quantidade de depoimentos.",
    pricing_model: "Assinatura (R$ 49 - R$ 99/mês)",
    target: "B2B (Infoprodutores)",
    sales_strategy: "Parcerias com plataformas de curso (Hotmart/Kiwify).",
    pdr: "Gravação de vídeo via browser (MediaRecorder API)."
  },
  {
    title: "Gerador Certificados em Lote",
    niche: "Educação",
    pain: "Gerar 100 certificados manualmente no Word é um inferno.",
    solution: "Upload de CSV + Template Imagem -> Disparo de emails com certificados personalizados.",
    why: "Ferramenta de produtividade pontual mas indispensável.",
    pricing_model: "Créditos ou Assinatura (R$ 49/mês)",
    target: "B2B (Organizadores de Eventos)",
    sales_strategy: "SEO 'gerador certificado online'.",
    pdr: "Manipulação de imagem/PDF no backend."
  },
  {
    title: "Protetor Anti-Pirataria Vídeo",
    niche: "Educação",
    pain: "Rateio de cursos e pirataria.",
    solution: "Player com marca d'água dinâmica (CPF/Nome) flutuando na tela. Desestimula gravação de tela.",
    why: "Proteção de receita do produtor. Solução mais barata que DRM complexo.",
    pricing_model: "Uso (R$ 199/mês)",
    target: "B2B (Infoprodutores)",
    sales_strategy: "Demonstração de segurança.",
    pdr: "Custom video player (HTML5) com overlay canvas."
  },
  {
    title: "Dashboard Unificado Infoprodutor",
    niche: "Finanças",
    pain: "Vendas espalhadas em Hotmart, Eduzz, Kiwify. Difícil ver fluxo de caixa.",
    solution: "Dashboard que agrega todas APIs e mostra faturamento real e previsibilidade de saques.",
    why: "Clareza financeira para quem escala.",
    pricing_model: "Assinatura (R$ 97/mês)",
    target: "B2B (Infoprodutores)",
    sales_strategy: "Marketing para 'gestão financeira digital'.",
    pdr: "Integração com múltiplas APIs de pagamento."
  },
  {
    title: "Criador Flashcards AI",
    niche: "Educação",
    pain: "Criar flashcards para Anki demora muito.",
    solution: "Upload PDF da apostila -> IA gera deck de flashcards pronto para exportar.",
    why: "Produtividade de estudo. Público estudante paga por tempo.",
    pricing_model: "Assinatura (R$ 19/mês)",
    target: "B2C (Estudantes/Concurseiros)",
    sales_strategy: "Influencers de estudo/concurso.",
    pdr: "LLM para extração de Q&A e formatação arquivo Anki."
  },
  {
    title: "Gamificação Desafios WhatsApp",
    niche: "Creator Economy",
    pain: "Engajamento cai em grupos de desafio de 21 dias.",
    solution: "Bot que lê provas (fotos) no grupo, dá pontos e gera ranking automático.",
    why: "Aumenta taxa de sucesso do aluno e LTV.",
    pricing_model: "Por grupo (R$ 97/mês)",
    target: "B2B (Lançadores de Desafios)",
    sales_strategy: "Venda direta para experts.",
    pdr: "Bot de leitura de mensagens e gamificação."
  },
  {
    title: "CertificatePress WP",
    niche: "Educação",
    pain: "Plugins de LMS WordPress têm certificados feios.",
    solution: "Plugin gerador de certificados bonitos com validação de autenticidade via QR Code.",
    why: "Agrega valor ao curso vendido.",
    pricing_model: "Anual (R$ 79/ano)",
    target: "B2B (Donos de site WP)",
    sales_strategy: "Marketplace WP.",
    pdr: "Plugin PHP GD Library."
  },
  {
    title: "Coletor Provas Sociais Vídeo",
    niche: "Marketing",
    pain: "Cliente não sabe gravar depoimento bom.",
    solution: "Link com teleprompter na tela que guia o cliente no que falar durante a gravação.",
    why: "Melhora qualidade e quantidade de depoimentos.",
    pricing_model: "Assinatura (R$ 97/mês)",
    target: "B2B (Lojistas/Experts)",
    sales_strategy: "Marketing de conteúdo sobre conversão.",
    pdr: "Web recording com overlay de texto."
  },
  {
    title: "Gerador Media Kit Dinâmico",
    niche: "Creator Economy",
    pain: "Media kit em PDF fica desatualizado rápido.",
    solution: "Página web 'MinhaMídia' conectada às APIs sociais que mostra números em tempo real.",
    why: "Profissionalismo para fechar publis.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2C (Influenciadores)",
    sales_strategy: "Viralização 'Powered By'.",
    pdr: "Integração APIs Instagram/TikTok/Youtube."
  },
  {
    title: "Filtro Comentários Hate",
    niche: "Creator Economy",
    pain: "Hate speech e spam nos comentários afetam saúde mental.",
    solution: "IA que modera e oculta comentários tóxicos automaticamente antes de você ler.",
    why: "Paz de espírito como serviço.",
    pricing_model: "Assinatura (R$ 29/mês)",
    target: "B2C (Creators Grandes)",
    sales_strategy: "Foco em saúde mental de creators.",
    pdr: "Análise de sentimento e API de moderação."
  },
  {
    title: "Ideation Bank Content",
    niche: "Creator Economy",
    pain: "Bloqueio criativo diário.",
    solution: "Monitor de tendências que sugere pautas quentes do seu nicho baseadas em dados.",
    why: "Produtividade e relevância.",
    pricing_model: "Assinatura (R$ 39/mês)",
    target: "B2C (Creators)",
    sales_strategy: "Conteúdo sobre 'como nunca ficar sem ideias'.",
    pdr: "Scraper de trends e agregador de notícias."
  },
  {
    title: "Link na Bio Captura",
    niche: "Marketing",
    pain: "Linktree não captura leads (emails).",
    solution: "Link na bio focado em conversão: campo de email em destaque integrado ao Mailchimp.",
    why: "Transforma seguidores em leads donos.",
    pricing_model: "Assinatura (R$ 29/mês)",
    target: "B2C (Creators/Lojistas)",
    sales_strategy: "Freemium com marca d'água.",
    pdr: "Landing page builder simplificado com integrações."
  },
  {
    title: "Transcritor Vídeo p/ Blog",
    niche: "Marketing",
    pain: "Conteúdo rico em vídeo morre lá. Não vira SEO.",
    solution: "IA transcreve vídeo e formata em post de blog estruturado (H1, H2) automaticamente.",
    why: "Reciclagem de conteúdo e tráfego orgânico.",
    pricing_model: "Assinatura (R$ 59/mês)",
    target: "B2B (Creators/Agências)",
    sales_strategy: "SEO content.",
    pdr: "Whisper API + LLM para formatação."
  },
  {
    title: "SocialRecap Freelancers",
    niche: "Marketing",
    pain: "Montar relatório mensal de redes sociais é chato e manual.",
    solution: "Gera relatório PDF bonito com métricas do mês automaticamente e envia pro cliente.",
    why: "Economia de tempo e profissionalismo na entrega.",
    pricing_model: "Assinatura (R$ 29 - R$ 79/mês)",
    target: "B2B (Social Medias)",
    sales_strategy: "Comunidades de social media.",
    pdr: "Agregador de métricas e gerador de PDF."
  },
  {
    title: "RoteiroFácil Youtube",
    niche: "Creator Economy",
    pain: "Roteiros ruins derrubam retenção do vídeo.",
    solution: "Editor de roteiro com templates de retenção (MrBeast style) e análise de ritmo via IA.",
    why: "Retenção = Dinheiro no YouTube.",
    pricing_model: "Assinatura (R$ 39/mês)",
    target: "B2C (Youtubers)",
    sales_strategy: "Parceria com escolas de videomakers.",
    pdr: "Editor de texto assistido por IA."
  },
  {
    title: "Legenda Fácil Shorts",
    niche: "Creator Economy",
    pain: "Legendar vídeos curtos manualmente é demorado.",
    solution: "Legendas automáticas animadas estilo TikTok/Reels em segundos.",
    why: "Vídeo sem legenda não retém. Ferramenta de produtividade massiva.",
    pricing_model: "Assinatura (R$ 22 - R$ 49/mês)",
    target: "B2C (Creators)",
    sales_strategy: "Watermark viral nos vídeos free.",
    pdr: "Transcrição timestamped e renderização de vídeo na nuvem."
  },
  {
    title: "Gerador Criativos Locais",
    niche: "Marketing",
    pain: "Pequeno negócio não sabe criar anúncio bonito.",
    solution: "Gerador de banners baseado em templates de alta conversão por nicho (Pizzaria, Pet).",
    why: "Democratiza o design profissional.",
    pricing_model: "Assinatura (R$ 97/mês)",
    target: "B2B (Negócios Locais)",
    sales_strategy: "Ads locais.",
    pdr: "Canvas manipulation com templates pré-definidos."
  },
  {
    title: "OnboardKit Agências",
    niche: "Produtividade",
    pain: "Onboarding de novo cliente em agência é bagunçado.",
    solution: "Portal do cliente para coletar senhas, branding e briefing de forma organizada.",
    why: "Primeira impressão profissional e segurança de dados.",
    pricing_model: "Assinatura (R$ 99/mês)",
    target: "B2B (Agências Digitais)",
    sales_strategy: "Conteúdo sobre processos de agência.",
    pdr: "Formulários seguros e gestão de tarefas."
  },
  {
    title: "SOP as a Service",
    niche: "Gestão",
    pain: "Processos não padronizados geram erro na escala.",
    solution: "Gestor de Playbooks que cria tarefas automáticas no Asana/Trello quando acionado.",
    why: "Garante qualidade na entrega repetitiva.",
    pricing_model: "Assinatura (R$ 249/mês)",
    target: "B2B (Agências/Empresas de Serviço)",
    sales_strategy: "Consultoria de processos.",
    pdr: "Integração com ferramentas de PM (Project Management)."
  },
  {
    title: "Gerador Propostas Design",
    niche: "Vendas",
    pain: "Propostas em PDF são estáticas e demoradas.",
    solution: "Propostas web interativas com blocos reutilizáveis e aceite digital.",
    why: "Aumenta conversão e velocidade comercial.",
    pricing_model: "Assinatura (R$ 29 - R$ 79/mês)",
    target: "B2B (Designers/Freelancers)",
    sales_strategy: "Freemium.",
    pdr: "Web page builder simplificado."
  },
  {
    title: "Briefing Mágico",
    niche: "Marketing",
    pain: "Cliente não sabe pedir o que quer.",
    solution: "Formulário visual interativo que extrai o gosto do cliente e monta moodboard.",
    why: "Reduz refação de projetos criativos.",
    pricing_model: "Assinatura (R$ 99/mês)",
    target: "B2B (Agências/Designers)",
    sales_strategy: "Demonstração visual.",
    pdr: "Formulário condicional com upload de imagens."
  },
  {
    title: "Compliance Imagens Ads",
    niche: "Jurídico",
    pain: "Agência usa imagem com licença vencida e toma processo.",
    solution: "Gestor de ativos que avisa quando licença da imagem vai vencer.",
    why: "Gestão de risco jurídico.",
    pricing_model: "Assinatura (R$ 399/mês)",
    target: "B2B (Agências Publicidade)",
    sales_strategy: "Venda direta B2B.",
    pdr: "DAM (Digital Asset Management) simplificado."
  },
  {
    title: "Roteiro Viagem Agentes",
    niche: "Turismo",
    pain: "Roteiros em Word são feios e pouco práticos.",
    solution: "Criador de roteiro visual que vira um app web para o viajante usar durante a viagem.",
    why: "Agrega valor ao serviço do agente de viagens.",
    pricing_model: "Assinatura (R$ 39 - R$ 99/mês)",
    target: "B2B (Agentes de Viagem)",
    sales_strategy: "Parcerias com operadoras.",
    pdr: "Timeline builder com integração de mapas."
  },
  {
    title: "Auditor Dead Links",
    niche: "Marketing",
    pain: "Afiliados perdem dinheiro mandando tráfego para links quebrados.",
    solution: "Robô que checa todos seus links de afiliado e avisa se algum quebrou ou produto esgotou.",
    why: "Proteção de receita passiva.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2B (Afiliados/Blogs)",
    sales_strategy: "Plugins WP.",
    pdr: "Crawler de verificação de status HTTP."
  },
  {
    title: "ConteúdoLocal Imob",
    niche: "Imobiliário",
    pain: "Imobiliárias precisam de conteúdo local mas não têm tempo.",
    solution: "Assinatura de posts prontos sobre o bairro (escolas, parques) e mercado local.",
    why: "Productized Service de marketing.",
    pricing_model: "Assinatura (R$ 299/mês)",
    target: "B2B (Imobiliárias Locais)",
    sales_strategy: "Venda local.",
    pdr: "Plataforma de distribuição de conteúdo."
  },
  {
    title: "Cálculo Comissões Vendas",
    niche: "Vendas",
    pain: "Calcular comissão complexa em planilha gera erro e desconfiança.",
    solution: "Software que puxa vendas e calcula comissão exata com painel para vendedor acompanhar.",
    why: "Transparência e motivação para o time comercial.",
    pricing_model: "Assinatura (R$ 249/mês)",
    target: "B2B (Pequenas Empresas)",
    sales_strategy: "LinkedIn Sales.",
    pdr: "Motor de cálculo financeiro configurável."
  },
  {
    title: "Kudos & Feedback Slack",
    niche: "RH & Gestão",
    pain: "Falta de reconhecimento em empresas remotas.",
    solution: "Bot Slack para enviar elogios públicos e feedbacks anônimos para gestão.",
    why: "Melhora clima e retenção.",
    pricing_model: "Por usuário (R$ 5/mês)",
    target: "B2B (Empresas Tech)",
    sales_strategy: "Slack App Directory.",
    pdr: "Slack Bolt App."
  },
  {
    title: "Organizador One-on-Ones",
    niche: "Gestão",
    pain: "Reuniões de 1:1 sem pauta e sem histórico são inúteis.",
    solution: "Pauta colaborativa e histórico de combinados para reuniões de liderança.",
    why: "Melhora qualidade da gestão.",
    pricing_model: "Por gestor (R$ 29/mês)",
    target: "B2B (Gestores)",
    sales_strategy: "Conteúdo sobre liderança.",
    pdr: "CRUD de notas compartilhadas."
  },
  {
    title: "Tracker Fuso Horário",
    niche: "Produtividade",
    pain: "Agendar reunião com time global é pesadelo matemático.",
    solution: "Visualizador de disponibilidade de time sobreposta em fusos diferentes.",
    why: "Resolve dor latente de times remotos.",
    pricing_model: "Time (R$ 15/mês)",
    target: "B2B (Equipes Remotas)",
    sales_strategy: "Product Hunt.",
    pdr: "Visualização de timeline com date-fns/timezone."
  },
  {
    title: "Onboarding Checklist Maker",
    niche: "RH & Gestão",
    pain: "Novo funcionário fica perdido sem saber o que fazer.",
    solution: "Criador de trilhas de onboarding com acompanhamento de progresso pelo RH.",
    why: "Acelera ramp-up do colaborador.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2B (RH)",
    sales_strategy: "LinkedIn RH.",
    pdr: "Sistema de LMS simplificado."
  },
  {
    title: "Gestão Exames Periódicos",
    niche: "RH & Gestão",
    pain: "Empresa perde prazo de exame médico e paga multa.",
    solution: "Alertas de vencimento de ASO e agendamento automático com clínicas.",
    why: "Compliance trabalhista.",
    pricing_model: "Por funcionário",
    target: "B2B (RH/DP)",
    sales_strategy: "Parceria com clínicas de trabalho.",
    pdr: "Gestão de datas e disparos de email."
  },
  {
    title: "Controle EPI Indústria",
    niche: "Gestão",
    pain: "Ficha de EPI em papel se perde e gera processo.",
    solution: "Entrega de EPI com assinatura digital no tablet e controle de validade.",
    why: "Segurança jurídica para indústria.",
    pricing_model: "Assinatura (R$ 199/mês)",
    target: "B2B (Pequenas Indústrias/Obras)",
    sales_strategy: "Venda técnica.",
    pdr: "App offline com assinatura digital."
  },
  {
    title: "Validador CNPJ API",
    niche: "Developer Tools",
    pain: "API da Receita é instável e difícil de integrar.",
    solution: "API Wrapper estável e rápida para consulta de dados de CNPJ.",
    why: "Devs pagam por conveniência e estabilidade.",
    pricing_model: "Uso (R$ 20 - R$ 100/mês)",
    target: "B2D (Desenvolvedores)",
    sales_strategy: "SEO técnico e GitHub.",
    pdr: "Proxy com cache agressivo e múltiplas fontes de dados."
  },
  {
    title: "Gerador Docs API",
    niche: "Developer Tools",
    pain: "Escrever documentação de API é chato e ela fica desatualizada.",
    solution: "Lê o código e gera site de documentação bonito automaticamente.",
    why: "Dev experience é essencial hoje.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2D (Dev Teams)",
    sales_strategy: "Integração CI/CD.",
    pdr: "Parser de código estático e gerador estático de site."
  },
  {
    title: "Status Page as Service",
    niche: "Developer Tools",
    pain: "Clientes reclamam no suporte quando sistema cai.",
    solution: "Página de status pública hospedada fora da sua infra para comunicar incidentes.",
    why: "Gestão de crise e transparência.",
    pricing_model: "Assinatura (R$ 29/mês)",
    target: "B2B (SaaS)",
    sales_strategy: "Footer 'Powered by'.",
    pdr: "Hospedagem isolada e sistema de incidentes."
  },
  {
    title: "Validador Acessibilidade",
    niche: "Developer Tools",
    pain: "Sites precisam ser acessíveis (WCAG) mas testar é difícil.",
    solution: "Scanner que aponta erros de acessibilidade e ensina como corrigir.",
    why: "Risco legal e inclusão.",
    pricing_model: "Assinatura (R$ 29/mês)",
    target: "B2D (Agências Web)",
    sales_strategy: "Ferramenta gratuita de diagnóstico.",
    pdr: "Crawler com regras de validação WCAG."
  },
  {
    title: "Roadmap Público Startup",
    niche: "Gestão",
    pain: "Clientes pedem features e não sabem o que está sendo feito.",
    solution: "Quadro público de roadmap onde clientes votam no que querem ver a seguir.",
    why: "Alinhamento de expectativa e feedback de produto.",
    pricing_model: "Assinatura (R$ 39/mês)",
    target: "B2B (SaaS)",
    sales_strategy: "Rodapé de apps.",
    pdr: "Kanban público com votação."
  },
  {
    title: "NPS One-Click SaaS",
    niche: "Gestão",
    pain: "Ninguém responde pesquisa de NPS por email.",
    solution: "Widget in-app que pergunta NPS com 1 clique dentro do software.",
    why: "Aumenta resposta drasticamente.",
    pricing_model: "Assinatura (R$ 49/mês)",
    target: "B2B (SaaS)",
    sales_strategy: "Inbound marketing.",
    pdr: "Script embedável leve."
  }
];
